### ISSUE TITLE
UI[bug fix]：send pageの一番下の行の食材が送信UIに被っている

### ISSUE THREAD

**Issue by shunsuke-tamura** [scla-sagauniv/tofu_in_hamburger_fe#11]
![スクリーンショット 2023-06-15 21 08 18](https://github.com/scla-sagauniv/tofu_in_hamburger_fe/assets/74412997/1bfec504-5541-4b51-8733-8f8ecb1e8609)

一番下の行に送信UIの縦の長さ分のmargin設けて、スクロールできるようにする

**Comment by shunsuke-tamura** [comment]
レスポンシブの関係で、一個一個のアイコンの大きさが変わるので、固定でmarginを置くなら、レスポンシブ対応入れて、一番アイコンが大きくなる時の表示と、小さくなる時の表示で違和感ないmarginを見つけなければいけないかも

それめんどくさいから、アイコンもボタンも何も表示しない行を余分に一行用意して、描画(中身は何もないので見えない)してmargin確保するのもいいかも

**Comment by sakupi01** [comment]
既存の送信UIコンポーネントからfixedプロパティを消去したコンポーネントを作成し，アイコンコンポーネント群の下に埋め込みvisibilityをhiddenにすることによって解消しました

> アイコンもボタンも何も表示しない行を余分に一行用意
を採用しようと思ったけどデータセットの数によって挿入するブランクのアイコンの数が変わる．．．の処理をするのがめんどくさかったので，確実に「送信UIコンポーネントの高さ分だけ」余白を設けられる上記の方法にしました（SEO的には大問題だと思いますが）

[https://github.com/scla-sagauniv/tofu_in_hamburger_fe/commit/0471a7dbae49d66d28ab9bd2a799e8cd8369bd6b](url)

**Comment by shunsuke-tamura** [comment]
リンクみっすってません？

**Comment by sakupi01** [comment]
あれれ！ごめんなさい！
[https://github.com/scla-sagauniv/tofu_in_hamburger_fe/commit/0471a7dbae49d66d28ab9bd2a799e8cd8369bd6b](https://github.com/scla-sagauniv/tofu_in_hamburger_fe/commit/0471a7dbae49d66d28ab9bd2a799e8cd8369bd6b)
