### ISSUE TITLE
UI[want do]：レスポンシブ対応

### ISSUE THREAD

**Issue by shunsuke-tamura** [scla-sagauniv/tofu_in_hamburger_fe#12]

**Comment by sakupi01** [comment]
頑張るー
アニメーションの実装とどっちが優先？

**Comment by shunsuke-tamura** [comment]
やってて楽しい方でいいよ
ハッカソンなんで

**Comment by sakupi01** [comment]
アニメーションで行き詰まったらレスポンシブに移行することにします

**Comment by sakupi01** [comment]
息抜きにレビューしてくれると嬉しいです
大丈夫だったらプルリク承認＆issue closeなど頼みます！
大丈夫じゃなかったら直すので
https://github.com/scla-sagauniv/tofu_in_hamburger_fe/pull/14

（あれ，最初アニメーションするって言ってたな．まあいいか！）
